 
controller_manager:
  ros__parameters:
    update_rate: 50.0

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_left"]
    right_wheel_names: ["wheel_right"]

    wheel_separation: 0.26
    wheel_radius: 0.0204

    publish_rate: 50.0
    use_stamped_vel: false
